output "user_arn" {
  description = "ARN of the local development IAM user"
  value       = aws_iam_user.local_dev.arn
}

output "access_key_id" {
  description = "Access key ID for local development"
  value       = aws_iam_access_key.local_dev.id
}

output "secret_access_key" {
  description = "Secret access key for local development"
  value       = aws_iam_access_key.local_dev.secret
  sensitive   = true
}

output "aws_region" {
  description = "AWS region for the credentials"
  value       = var.aws_region
}

output "env_file_content" {
  description = "Content for .env.local file"
  value       = <<-EOT
    # Local Development AWS Credentials
    # Generated by: terraform output -raw env_file_content > .env.local

    AWS_ACCESS_KEY_ID=${aws_iam_access_key.local_dev.id}
    AWS_SECRET_ACCESS_KEY=${aws_iam_access_key.local_dev.secret}
    AWS_REGION=${var.aws_region}

    # DynamoDB Tables
    DYNAMODB_ASSET_TABLE=streaming-agents-asset-state
    DYNAMODB_INCIDENTS_TABLE=streaming-agents-incidents
    DYNAMODB_HISTORY_TABLE=streaming-agents-asset-history

    # Kinesis Streams
    KINESIS_TELEMETRY_STREAM=streaming-agents-r17-telemetry
    KINESIS_INGESTED_STREAM=streaming-agents-r17-ingested
    KINESIS_RISK_EVENTS_STREAM=streaming-agents-r17-risk-events
  EOT
  sensitive   = true
}
